[build]
  command = "next build"

[[plugins]]
  package = "@netlify/plugin-nextjs"

[[headers]]
  for = "/*"
  [headers.values]
    Clear-Site-Data = '"cache", "cookies", "storage", "executionContexts"'

[[redirects]]
  from = "https://techwrench.co/*"
  to = "https://www.techwrench.co/:splat"
  status = 301
  force = true
